apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemonset
  labels:
    name: mydaemonset
spec:
  template:
    metadata:
      labels:
        name: mynginx
    spec:
      containers:
      - name: mynginx
        image: nginx
  selector:
    matchLabels:
      name: mynginx